from dataclasses import dataclass, field
from src.Documents.Document import Document


@dataclass
class DeathRegistrationWorksheet(Document):
    name = "Death Registration Worksheet"
    fields: list[str] = field(
        default_factory=lambda: [
            "DECEDENT'S FIRST NAME",
            "DECEDENT'S MIDDLE NAME",
            "DECEDENT'S LAST NAME",
            "DECEDENT'S SUFFIX",
            "DECEDENT's AKA'S",
            "SOCIAL SECURITY NUMBER",
            "DATE OF DEATH (mm/dd/yyyy)",
            "DATE OF BIRTH (mm/dd/yyyy)",
            "AGE",
            "DECEDENT'S BIRTH CITY OR TOWN",
            "DECEDENT'S BIRTH COUNTY",
            "DECEDENT'S BIRTH STATE",
            "DECEDENT'S BIRTH COUNTRY",
            "EVER IN U.S. ARMED FORCES?",
            "DECEDENT'S NAME PRIOR TO FIRST MARRIAGE",
            "HRRF (HUMAN REMAINS RELEASE FORM)",
            "DECEDENT'S RESIDENCE STREET ADDRESS",
            "ZIP CODE",
            "RESIDENCE CITY",
            "RESIDENCE COUNTY",
            "RESIDENCE STATE",
            "RESIDENCE COUNTRY",
            "IN CITY LIMITS",
            "HOW LONG IN THE STATE OF ARIZONA?",
            "RESIDED IN AZ. TRIBAL COMMUNITY?",
            "MARITAL STATUS",
            "FIRST NAME OF SURVIVING SPOUSE",
            "MIDDLE NAME OF SURVIVING SPOUSE",
            "LAST NAME OF SURVIVING SPOUSE",
            "SUFFIX (SURVIVING SPOUSE)",
            "LAST NAME OF SURVIVING SPOUSE PRIOR TO FIRST MARRIAGE",
            "FATHER'S FIRST NAME",
            "FATHER'S MIDDLE NAME",
            "FATHER'S LAST NAME",
            "SUFFIX (FATHER)",
            "MOTHER'S FIRST NAME",
            "MOTHER'S MIDDLE NAME",
            "MOTHER'S LAST NAME PRIOR TO FIRST MARRIAGE",
            "SUFFIX (MOTHER)",
            "INFORMANT'S FIRST NAME",
            "INFORMANT'S MIDDLE NAME",
            "INFORMANT'S LAST NAME",
            "SUFFIX (INFORMANT)",
            "RELATIONSHIP TO DECEDENT",
            "INFORMANT'S EMAIL ADDRESS",
            "INFORMANT'S PHONE NUMBER",
            "INFORMANT'S MAILING ADDRESS",
            "DATE OF DISPOSITION",
            "PLACE OF DISPOSITION - NAME OF FIRST DISPOSITION FACILITY",
            "PLACE OF DISPOSITION - NAME OF SECOND DISPOSITION FACILITY",
            "NAME OF FUNERAL DIRECTOR",
            "LICENSE NUMBER",
            "NAME OF FUNERAL HOME",
            "ADDRESS OF FUNERAL HOME OR OTHER RESPONSIBLE PARTY",
            "OTHER RESPONSIBLE PARTY RELATIONSHIP",
            "DECEDENT'S OCCUPATION",
            "TYPE OF PLACE OF DEATH",
            "PLACE OF DEATH FACILITY NAME" "PLACE OF DEATH FACILITY ADDRESS",
            "SPECIFY OTHER INSTITUTION OR ADDRESS WHERE DEATH OCCURRED",
            "CERTIFIER TYPE",
            "CERTIFIER'S LICENSE NUMBER",
            "CERTIFIER'S NAME",
            "CERTIFIER'S TITLE",
            "CERTIFIER'S ADDRESS",
            "CERTIFIER'S ZIP CODE",
            "CERTIFIER'S CITY, TOWN, OR LOCATION",
            "CERTIFIER'S STATE",
            "CERTIFIER'S COUNTRY",
            "NAME OF ALTERNATE CERTIFIER",
            "TELEPHONE NUMBER",
            "FAX NUMBER",
            "EMAIL ADDRESS",
            "DATE SIGNED",
        ]
    )

    def ___str__(self):
        return "Death Registration Worksheet"
